defmodule Muro.EmitCTest do
  use ExUnit.Case, async: false

  import ExUnit.CaptureIO

  test "mix muro.emit --backend elixir matches emit_file" do
    path = "examples/half_ok.muro"
    assert {:ok, src} = Muro.emit_file(path, HalfOk)
    assert src =~ "def plus"
    assert src =~ "def half"
    refute src =~ "defp pred"
    refute src =~ "def half_ok"

    out = capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "elixir"]) end)
    assert String.trim_trailing(out) == String.trim_trailing(src)

    out = capture_io(fn -> Mix.Tasks.Muro.Emit.run([path]) end)
    assert String.trim_trailing(out) == String.trim_trailing(src)
  end

  test "mix muro.emit --backend c compiles half_ok" do
    dir = tmp_dir()
    path = Path.join(dir, "half_ok.muro")
    File.cp!("examples/half_ok.muro", path)

    out = capture_io(fn -> Mix.Tasks.Muro.Emit.run([path, "--backend", "c"]) end)

    h = Path.join(dir, "half_ok.h")
    c = Path.join(dir, "half_ok.c")
    assert out =~ h
    assert out =~ c

    header = File.read!(h)
    source = File.read!(c)

    assert header =~ "/* generated by muro — do not edit */"
    assert header =~ "struct muro_nat { uint8_t tag; muro_nat *suc; }; /* 0 = zero, 1 = suc */"
    assert header =~ "muro_nat *half(muro_nat *n);"
    assert header =~ "muro_nat *plus(muro_nat *n, muro_nat *m);"
    refute header =~ "IsEven"
    refute header =~ "half_ok("

    assert source =~ "muro_zero"
    assert source =~ "muro_suc"
    refute source =~ "static muro_nat *half"
    assert source =~ "half("

    cc!(dir, "half_ok.c", "half_ok.o")
  end

  test "a run Stream is refused by C and still emitted as Elixir" do
    assert_raise Mix.Error, ~r/c:stream/, fn ->
      Mix.Tasks.Muro.Emit.run(["examples/zeros.muro", "--backend", "c"])
    end

    refute File.exists?("examples/zeros.h")
    refute File.exists?("examples/zeros.c")

    assert {:ok, src} = Muro.emit_file("examples/zeros.muro", Zeros)
    assert src =~ "Stream.unfold"

    out =
      capture_io(fn ->
        Mix.Tasks.Muro.Emit.run(["examples/zeros.muro", "--backend", "elixir"])
      end)

    assert out =~ "Stream.unfold"
  end

  test "I64 and Tensor are refused by C and still emitted as Elixir" do
    assert_raise Mix.Error, ~r/c:machine/, fn ->
      Mix.Tasks.Muro.Emit.run(["examples/nx_add.muro", "--backend", "c"])
    end

    assert {:ok, src} = Muro.emit_file("examples/nx_add.muro", NxAdd)
    assert src =~ "Nx.add"
  end

  test "run internal is static and list data compiles" do
    dir = tmp_dir()

    internal = Path.join(dir, "internal_ok.muro")
    File.cp!("examples/internal_ok.muro", internal)
    capture_io(fn -> Mix.Tasks.Muro.Emit.run([internal, "--backend", "c"]) end)

    header = File.read!(Path.join(dir, "internal_ok.h"))
    source = File.read!(Path.join(dir, "internal_ok.c"))
    assert header =~ "muro_nat *inc(muro_nat *n);"
    refute header =~ "step"
    assert source =~ "static muro_nat *step(muro_nat *n)"
    cc!(dir, "internal_ok.c", "internal_ok.o")

    list = Path.join(dir, "list.muro")
    File.cp!("examples/list.muro", list)
    capture_io(fn -> Mix.Tasks.Muro.Emit.run([list, "--backend", "c"]) end)
    list_h = File.read!(Path.join(dir, "list.h"))
    assert list_h =~ "muro_list"
    assert list_h =~ "muro_nat *length(muro_list *xs);"
    cc!(dir, "list.c", "list.o")
  end

  defp tmp_dir do
    dir = Path.join(System.tmp_dir!(), "muro_c_#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)
    on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  defp cc!(dir, src, obj) do
    {out, status} =
      System.cmd("cc", ["-c", src, "-o", obj], cd: dir, stderr_to_stdout: true)

    assert status == 0, out
  end
end
