------------------------------------------------------------------------
-- Conversion for the ⊢ fragment.
--
-- Two relations, one strategy and one equivalence:
--
-- ⟶  one-step weak-head reduction, exactly the strategy of Check.whnf:
--      δ    def i unfolds when allowedDef permits the mode
--      β    app (lam _ _ t) a ⟶ inst t a
--      ι    mNat ze / mNat (su _) / mUnit one / rwt rfl /
--           letp (pair a b) t / mData (ctor i j a₁ … aₙ) with a j-th branch
--      ann  ann e A ⟶ e
--    ⟶ is deterministic (det). Nf / Ne are its normal and neutral
--    forms; Consistency uses ⟶ for progress.
--
-- ≈  the equivalence generated by parallel reduction ⇛ (Muro.Reduction),
--    which contracts the same redexes anywhere in a term, under binders
--    included. ≈ is therefore a congruence and is closed under
--    substitution (≈-sub, ≈-inst), which the substitution lemma of the
--    metatheory needs; ⟶ ⊆ ⇛, so whnf steps are conversions. Because ⇛
--    is confluent, ≈ is joinability (≈→join): two rigid forms with
--    different heads are never convertible (≈-shape), and Π / ≡ are
--    injective up to ≈. No normalisation is assumed anywhere.
--
-- ≈ does not contain η, or any rule for ν / Nx (those terms are inert).
-- Pairs are eliminated by letp only. Check.conv is the algorithm; it
-- compares subterms after whnf and is expected to be sound for ≈.
--
-- Data. A constructor application ctor i j a₁ … aₙ and a data type
-- dty i p₁ … pₙ are spines (Muro.Spine) with a rigid head: they are
-- normal for ⟶, they only reduce to spines with the same head under ⇛,
-- and two convertible dty spines have the same head and convertible
-- arguments (≈-dty-inj). Nothing is assumed about the signature here.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module Muro.Convert where

open import Data.Bool.Base using (Bool; true; false)
open import Data.Empty using (⊥; ⊥-elim)
open import Data.Fin.Base using (Fin)
open import Data.List.Base using (List; []; _∷_)
open import Data.Nat.Base using (ℕ; suc)
open import Data.Product.Base using (Σ; _×_; _,_; ∃)
open import Data.Sum.Base using (_⊎_; inj₁; inj₂)
open import Relation.Binary.PropositionalEquality.Core
  using (_≡_; refl; sym; trans; cong; subst)

open import Muro.Base
open import Muro.Syntax
open import Muro.Subst
open import Muro.Env
open import Muro.Spine
open import Muro.Reduction

ok-inj : ∀ {A : Set} {x y : A} → ok x ≡ ok y → x ≡ y
ok-inj refl = refl

------------------------------------------------------------------------
-- Terms outside the fragment. They never reduce.
------------------------------------------------------------------------

data Foreign {n} : Tm n → Set where
  f-nu     : ∀ {F} → Foreign (nu F)
  f-unf    : ∀ {s f} → Foreign (unf s f)
  f-ucons  : ∀ {s} → Foreign (ucons s)
  f-i64    : Foreign i64
  f-f32ty  : Foreign f32ty
  f-tensor : ∀ {d s} → Foreign (tensor d s)
  f-addi   : ∀ {x y} → Foreign (addi x y)
  f-muli   : ∀ {x y} → Foreign (muli x y)
  f-addt   : ∀ {t u} → Foreign (addt t u)
  f-toi64  : ∀ {t} → Foreign (toi64 t)
  f-packi  : ∀ {x y} → Foreign (packi x y)
  f-alw    : ∀ {A P s} → Foreign (alw A P s)
  f-bsm    : ∀ {A a b} → Foreign (bsm A a b)

------------------------------------------------------------------------
-- Neutral and normal terms for this strategy (weak head: arguments,
-- branches, and the body of su are not looked at). Nf is what
-- Consistency inverts. Neither is complete: some ill-typed terms are
-- stuck without being Ne (a match on a constructor without a branch).
------------------------------------------------------------------------

data Ne (σ : Sig) (m : Mode) {n} : Tm n → Set
data Nf (σ : Sig) (m : Mode) {n} : Tm n → Set

data Ne σ m where
  ne-var     : ∀ {x} → Ne σ m (var x)
  ne-def     : ∀ {i}
    → (∀ {d} → lookupDef σ i ≡ ok d → allowedDef (Def.dmode d) m ≡ true → ⊥)
    → Ne σ m (def i)
  ne-app     : ∀ {f a} → Ne σ m f → Ne σ m (app f a)
  ne-mNat    : ∀ {e P z s} → Ne σ m e → Ne σ m (mNat e P z s)
  ne-mUnit   : ∀ {e P u} → Ne σ m e → Ne σ m (mUnit e P u)
  ne-mEmp    : ∀ {e P} → Ne σ m e → Ne σ m (mEmp e P)
  ne-rwt     : ∀ {eq P t} → Ne σ m eq → Ne σ m (rwt eq P t)
  ne-mData   : ∀ {e P bs} → Ne σ m e → Ne σ m (mData e P bs)
  ne-letp    : ∀ {e t} → Ne σ m e → Ne σ m (letp e t)
  ne-foreign : ∀ {t} → Foreign t → Ne σ m t

data Nf σ m where
  nf-ne    : ∀ {t} → Ne σ m t → Nf σ m t
  nf-typ   : Nf σ m typ
  nf-pi    : ∀ {q A B} → Nf σ m (pi q A B)
  nf-lam   : ∀ {q A t} → Nf σ m (lam q A t)
  nf-nat   : Nf σ m nat
  nf-ze    : Nf σ m ze
  nf-su    : ∀ {t} → Nf σ m (su t)
  nf-unit  : Nf σ m unit
  nf-one   : Nf σ m one
  nf-empty : Nf σ m empty
  nf-idt   : ∀ {A a b} → Nf σ m (idt A a b)
  nf-rfl   : Nf σ m rfl
  nf-prod  : ∀ {A B} → Nf σ m (prod A B)
  nf-pair  : ∀ {a b} → Nf σ m (pair a b)
  nf-ctor  : ∀ {i j as e} → Spine (ctor i j) as e → Nf σ m e
  nf-dty   : ∀ {i as e} → Spine (dty i) as e → Nf σ m e

------------------------------------------------------------------------
-- One-step reduction.
------------------------------------------------------------------------

infix 3 _⊢[_]_⟶_ _⊢[_]_⟶*_ _⊢[_]_≈_

data _⊢[_]_⟶_ (σ : Sig) (m : Mode) {n} : Tm n → Tm n → Set where
  δ : ∀ {i d}
    → lookupDef σ i ≡ ok d
    → allowedDef (Def.dmode d) m ≡ true
    → σ ⊢[ m ] def i ⟶ closed (Def.dbody d)

  β : ∀ {q A t a}
    → σ ⊢[ m ] app (lam q A t) a ⟶ inst t a

  app-f : ∀ {f f′ a}
    → σ ⊢[ m ] f ⟶ f′
    → σ ⊢[ m ] app f a ⟶ app f′ a

  ιz : ∀ {P z s}
    → σ ⊢[ m ] mNat ze P z s ⟶ z

  ιs : ∀ {u P z s}
    → σ ⊢[ m ] mNat (su u) P z s ⟶ inst s u

  mNat-e : ∀ {e e′ P z s}
    → σ ⊢[ m ] e ⟶ e′
    → σ ⊢[ m ] mNat e P z s ⟶ mNat e′ P z s

  ιtt : ∀ {P u}
    → σ ⊢[ m ] mUnit one P u ⟶ u

  mUnit-e : ∀ {e e′ P u}
    → σ ⊢[ m ] e ⟶ e′
    → σ ⊢[ m ] mUnit e P u ⟶ mUnit e′ P u

  mEmp-e : ∀ {e e′ P}
    → σ ⊢[ m ] e ⟶ e′
    → σ ⊢[ m ] mEmp e P ⟶ mEmp e′ P

  ιrfl : ∀ {P t}
    → σ ⊢[ m ] rwt rfl P t ⟶ t

  rwt-e : ∀ {eq eq′ P t}
    → σ ⊢[ m ] eq ⟶ eq′
    → σ ⊢[ m ] rwt eq P t ⟶ rwt eq′ P t

  ann-e : ∀ {e A}
    → σ ⊢[ m ] ann e A ⟶ e

  ι-data : ∀ {i j as e P bs b}
    → Spine (ctor i j) as e
    → lookupList bs j ≡ ok b
    → σ ⊢[ m ] mData e P bs ⟶ appsFrom b as

  mData-e : ∀ {e e′ P bs}
    → σ ⊢[ m ] e ⟶ e′
    → σ ⊢[ m ] mData e P bs ⟶ mData e′ P bs

  ι-letp : ∀ {a b t}
    → σ ⊢[ m ] letp (pair a b) t ⟶ inst₂ t a b

  letp-e : ∀ {e e′ t}
    → σ ⊢[ m ] e ⟶ e′
    → σ ⊢[ m ] letp e t ⟶ letp e′ t

------------------------------------------------------------------------
-- Normal forms do not step.
------------------------------------------------------------------------

foreign-no-step : ∀ {σ m n} {t u : Tm n} → Foreign t → σ ⊢[ m ] t ⟶ u → ⊥
foreign-no-step f-nu     ()
foreign-no-step f-unf    ()
foreign-no-step f-ucons  ()
foreign-no-step f-i64    ()
foreign-no-step f-f32ty  ()
foreign-no-step f-tensor ()
foreign-no-step f-addi   ()
foreign-no-step f-muli   ()
foreign-no-step f-addt   ()
foreign-no-step f-toi64  ()
foreign-no-step f-packi  ()
foreign-no-step f-alw    ()
foreign-no-step f-bsm    ()

-- A spine with a data head does not step: the head is not a λ.
Spine-no-step : ∀ {σ m n} {h : Tm n} {as e u}
  → DHead h → Spine h as e → σ ⊢[ m ] e ⟶ u → ⊥
Spine-no-step dh-ctor sp-[] ()
Spine-no-step dh-dty sp-[] ()
Spine-no-step hd (sp-snoc sp) β = Spine-lam hd sp
Spine-no-step hd (sp-snoc sp) (app-f s) = Spine-no-step hd sp s

ne-no-step : ∀ {σ m n} {t u : Tm n} → Ne σ m t → σ ⊢[ m ] t ⟶ u → ⊥
nf-no-step : ∀ {σ m n} {t u : Tm n} → Nf σ m t → σ ⊢[ m ] t ⟶ u → ⊥

-- A neutral term is not a constructor application.
ne-Spine : ∀ {σ m n} {i j} {as : List (Tm n)} {e}
  → Ne σ m e → Spine (ctor i j) as e → ⊥
ne-Spine (ne-foreign ()) sp-[]
ne-Spine (ne-app ne) (sp-snoc sp) = ne-Spine ne sp
ne-Spine (ne-foreign ()) (sp-snoc sp)

ne-no-step ne-var ()
ne-no-step (ne-def stuck) (δ lk al) = stuck lk al
ne-no-step (ne-app (ne-foreign ())) β
ne-no-step (ne-app nf) (app-f s) = ne-no-step nf s
ne-no-step (ne-mNat (ne-foreign ())) ιz
ne-no-step (ne-mNat (ne-foreign ())) ιs
ne-no-step (ne-mNat ne) (mNat-e s) = ne-no-step ne s
ne-no-step (ne-mUnit (ne-foreign ())) ιtt
ne-no-step (ne-mUnit ne) (mUnit-e s) = ne-no-step ne s
ne-no-step (ne-mEmp ne) (mEmp-e s) = ne-no-step ne s
ne-no-step (ne-rwt (ne-foreign ())) ιrfl
ne-no-step (ne-rwt ne) (rwt-e s) = ne-no-step ne s
ne-no-step (ne-mData ne) (ι-data sp _) = ne-Spine ne sp
ne-no-step (ne-mData ne) (mData-e s) = ne-no-step ne s
ne-no-step (ne-letp (ne-foreign ())) ι-letp
ne-no-step (ne-letp ne) (letp-e s) = ne-no-step ne s
ne-no-step (ne-foreign f) s = foreign-no-step f s

nf-no-step (nf-ne ne) s = ne-no-step ne s
nf-no-step nf-typ ()
nf-no-step nf-pi ()
nf-no-step nf-lam ()
nf-no-step nf-nat ()
nf-no-step nf-ze ()
nf-no-step nf-su ()
nf-no-step nf-unit ()
nf-no-step nf-one ()
nf-no-step nf-empty ()
nf-no-step nf-idt ()
nf-no-step nf-rfl ()
nf-no-step nf-prod ()
nf-no-step nf-pair ()
nf-no-step (nf-ctor sp) s = Spine-no-step dh-ctor sp s
nf-no-step (nf-dty sp) s = Spine-no-step dh-dty sp s

------------------------------------------------------------------------
-- Determinism.
------------------------------------------------------------------------

det : ∀ {σ m n} {t u v : Tm n}
  → σ ⊢[ m ] t ⟶ u → σ ⊢[ m ] t ⟶ v → u ≡ v
det (δ lk _) (δ lk′ _) with ok-inj (trans (sym lk) lk′)
... | refl = refl
det β β = refl
det β (app-f ())
det (app-f ()) β
det (app-f s) (app-f s′) = cong (λ f → app f _) (det s s′)
det ιz ιz = refl
det ιz (mNat-e ())
det ιs ιs = refl
det ιs (mNat-e ())
det (mNat-e ()) ιz
det (mNat-e ()) ιs
det (mNat-e s) (mNat-e s′) = cong (λ e → mNat e _ _ _) (det s s′)
det ιtt ιtt = refl
det ιtt (mUnit-e ())
det (mUnit-e ()) ιtt
det (mUnit-e s) (mUnit-e s′) = cong (λ e → mUnit e _ _) (det s s′)
det (mEmp-e s) (mEmp-e s′) = cong (λ e → mEmp e _) (det s s′)
det ιrfl ιrfl = refl
det ιrfl (rwt-e ())
det (rwt-e ()) ιrfl
det (rwt-e s) (rwt-e s′) = cong (λ e → rwt e _ _) (det s s′)
det ann-e ann-e = refl
det (ι-data sp lk) (ι-data sp′ lk′) with Spine-unique head-ctor head-ctor sp sp′
... | refl , refl with ok-inj (trans (sym lk) lk′)
...   | refl = refl
det (ι-data sp _) (mData-e s) = ⊥-elim (Spine-no-step dh-ctor sp s)
det (mData-e s) (ι-data sp _) = ⊥-elim (Spine-no-step dh-ctor sp s)
det (mData-e s) (mData-e s′) = cong (λ e → mData e _ _) (det s s′)
det ι-letp ι-letp = refl
det ι-letp (letp-e ())
det (letp-e ()) ι-letp
det (letp-e s) (letp-e s′) = cong (λ e → letp e _) (det s s′)

------------------------------------------------------------------------
-- Reflexive-transitive closure.
------------------------------------------------------------------------

data _⊢[_]_⟶*_ (σ : Sig) (m : Mode) {n} : Tm n → Tm n → Set where
  ⟶*-refl : ∀ {t} → σ ⊢[ m ] t ⟶* t
  ⟶*-step : ∀ {t u v} → σ ⊢[ m ] t ⟶ u → σ ⊢[ m ] u ⟶* v → σ ⊢[ m ] t ⟶* v

⟶*-trans : ∀ {σ m n} {t u v : Tm n}
  → σ ⊢[ m ] t ⟶* u → σ ⊢[ m ] u ⟶* v → σ ⊢[ m ] t ⟶* v
⟶*-trans ⟶*-refl r = r
⟶*-trans (⟶*-step s r) r′ = ⟶*-step s (⟶*-trans r r′)

-- Two reduction sequences from one term are ordered.
det* : ∀ {σ m n} {t u v : Tm n}
  → σ ⊢[ m ] t ⟶* u → σ ⊢[ m ] t ⟶* v
  → (σ ⊢[ m ] u ⟶* v) ⊎ (σ ⊢[ m ] v ⟶* u)
det* ⟶*-refl r = inj₁ r
det* (⟶*-step s r) ⟶*-refl = inj₂ (⟶*-step s r)
det* (⟶*-step s r) (⟶*-step s′ r′) with det s s′
... | refl = det* r r′

nf-⟶* : ∀ {σ m n} {t u : Tm n} → Nf σ m t → σ ⊢[ m ] t ⟶* u → u ≡ t
nf-⟶* _ ⟶*-refl = refl
nf-⟶* nf (⟶*-step s _) = ⊥-elim (nf-no-step nf s)

------------------------------------------------------------------------
-- Weak-head steps are parallel steps.
------------------------------------------------------------------------

⟶⊆⇛ : ∀ {σ m n} {t u : Tm n} → σ ⊢[ m ] t ⟶ u → σ ⊢[ m ] t ⇛ u
⟶⊆⇛ (δ lk al) = ⇛-δ lk al
⟶⊆⇛ β = ⇛-β (⇛-refl _) (⇛-refl _)
⟶⊆⇛ (app-f s) = ⇛-app (⟶⊆⇛ s) (⇛-refl _)
⟶⊆⇛ ιz = ⇛-ιz (⇛-refl _)
⟶⊆⇛ ιs = ⇛-ιs (⇛-refl _) (⇛-refl _)
⟶⊆⇛ (mNat-e s) = ⇛-mNat (⟶⊆⇛ s) (⇛-refl _) (⇛-refl _) (⇛-refl _)
⟶⊆⇛ ιtt = ⇛-ιtt (⇛-refl _)
⟶⊆⇛ (mUnit-e s) = ⇛-mUnit (⟶⊆⇛ s) (⇛-refl _) (⇛-refl _)
⟶⊆⇛ (mEmp-e s) = ⇛-mEmp (⟶⊆⇛ s) (⇛-refl _)
⟶⊆⇛ ιrfl = ⇛-ιrfl (⇛-refl _)
⟶⊆⇛ (rwt-e s) = ⇛-rwt (⟶⊆⇛ s) (⇛-refl _) (⇛-refl _)
⟶⊆⇛ ann-e = ⇛-ann (⇛-refl _)
⟶⊆⇛ (ι-data sp lk) = ⇛-ιdata sp lk (⇛L-refl _) (⇛-refl _)
⟶⊆⇛ (mData-e s) = ⇛-mData (⟶⊆⇛ s) (⇛-refl _) (⇛L-refl _)
⟶⊆⇛ ι-letp = ⇛-ιletp (⇛-refl _) (⇛-refl _) (⇛-refl _)
⟶⊆⇛ (letp-e s) = ⇛-letp (⟶⊆⇛ s) (⇛-refl _)

⟶*⊆⇛* : ∀ {σ m n} {t u : Tm n} → σ ⊢[ m ] t ⟶* u → σ ⊢[ m ] t ⇛* u
⟶*⊆⇛* ⟶*-refl = ⇛*-refl
⟶*⊆⇛* (⟶*-step s r) = ⇛*-step (⟶⊆⇛ s) (⟶*⊆⇛* r)

------------------------------------------------------------------------
-- Conversion: the equivalence generated by ⇛.
------------------------------------------------------------------------

data _⊢[_]_≈_ (σ : Sig) (m : Mode) {n} : Tm n → Tm n → Set where
  ≈-step  : ∀ {t u} → σ ⊢[ m ] t ⇛ u → σ ⊢[ m ] t ≈ u
  ≈-refl  : ∀ {t} → σ ⊢[ m ] t ≈ t
  ≈-sym   : ∀ {t u} → σ ⊢[ m ] t ≈ u → σ ⊢[ m ] u ≈ t
  ≈-trans : ∀ {t u v} → σ ⊢[ m ] t ≈ u → σ ⊢[ m ] u ≈ v → σ ⊢[ m ] t ≈ v

⇛*→≈ : ∀ {σ m n} {t u : Tm n} → σ ⊢[ m ] t ⇛* u → σ ⊢[ m ] t ≈ u
⇛*→≈ ⇛*-refl = ≈-refl
⇛*→≈ (⇛*-step s r) = ≈-trans (≈-step s) (⇛*→≈ r)

⟶→≈ : ∀ {σ m n} {t u : Tm n} → σ ⊢[ m ] t ⟶ u → σ ⊢[ m ] t ≈ u
⟶→≈ s = ≈-step (⟶⊆⇛ s)

⟶*→≈ : ∀ {σ m n} {t u : Tm n} → σ ⊢[ m ] t ⟶* u → σ ⊢[ m ] t ≈ u
⟶*→≈ r = ⇛*→≈ (⟶*⊆⇛* r)

-- Joinability: by confluence, convertible terms have a common reduct.
≈→join : ∀ {σ m n} {t u : Tm n}
  → σ ⊢[ m ] t ≈ u
  → ∃ λ v → (σ ⊢[ m ] t ⇛* v) × (σ ⊢[ m ] u ⇛* v)
≈→join (≈-step s) = _ , ⇛*-one s , ⇛*-refl
≈→join ≈-refl = _ , ⇛*-refl , ⇛*-refl
≈→join (≈-sym c) with ≈→join c
... | v , a , b = v , b , a
≈→join (≈-trans c c′) with ≈→join c | ≈→join c′
... | v , tv , uv | w , uw , sw with confluence uv uw
...   | x , vx , wx = x , ⇛*-trans tv vx , ⇛*-trans sw wx

join→≈ : ∀ {σ m n} {t u v : Tm n}
  → σ ⊢[ m ] t ⇛* v → σ ⊢[ m ] u ⇛* v → σ ⊢[ m ] t ≈ u
join→≈ tv uv = ≈-trans (⇛*→≈ tv) (≈-sym (⇛*→≈ uv))

------------------------------------------------------------------------
-- ≈ is a congruence, closed under substitution and renaming, and
-- monotone in the mode.
------------------------------------------------------------------------

≈-sub : ∀ {σ m n k} (τ : Fin n → Tm k) {t u : Tm n}
  → σ ⊢[ m ] t ≈ u → σ ⊢[ m ] sub τ t ≈ sub τ u
≈-sub τ (≈-step s) = ≈-step (⇛-sub-r τ s)
≈-sub τ ≈-refl = ≈-refl
≈-sub τ (≈-sym c) = ≈-sym (≈-sub τ c)
≈-sub τ (≈-trans c c′) = ≈-trans (≈-sub τ c) (≈-sub τ c′)

≈-ren : ∀ {σ m n k} (ρ : Fin n → Fin k) {t u : Tm n}
  → σ ⊢[ m ] t ≈ u → σ ⊢[ m ] ren ρ t ≈ ren ρ u
≈-ren ρ (≈-step s) = ≈-step (⇛-ren ρ s)
≈-ren ρ ≈-refl = ≈-refl
≈-ren ρ (≈-sym c) = ≈-sym (≈-ren ρ c)
≈-ren ρ (≈-trans c c′) = ≈-trans (≈-ren ρ c) (≈-ren ρ c′)

-- The substituted term may be converted.
≈-inst : ∀ {σ m n} (t : Tm (suc n)) {a a′ : Tm n}
  → σ ⊢[ m ] a ≈ a′ → σ ⊢[ m ] inst t a ≈ inst t a′
≈-inst t (≈-step s) = ≈-step (⇛-sub-l t (⇛σ-inst s))
≈-inst t ≈-refl = ≈-refl
≈-inst t (≈-sym c) = ≈-sym (≈-inst t c)
≈-inst t (≈-trans c c′) = ≈-trans (≈-inst t c) (≈-inst t c′)

≈-inst₂ : ∀ {σ m n} {t t′ : Tm (suc n)} {a a′ : Tm n}
  → σ ⊢[ m ] t ≈ t′ → σ ⊢[ m ] a ≈ a′ → σ ⊢[ m ] inst t a ≈ inst t′ a′
≈-inst₂ {t′ = t′} {a = a} ct ca = ≈-trans (≈-sub (instσ a) ct) (≈-inst t′ ca)

≈-mode : ∀ {σ m m′ n} {t u : Tm n} → m ≤ᵐ m′ → σ ⊢[ m ] t ≈ u → σ ⊢[ m′ ] t ≈ u
≈-mode h (≈-step s) = ≈-step (⇛-mode h s)
≈-mode h ≈-refl = ≈-refl
≈-mode h (≈-sym c) = ≈-sym (≈-mode h c)
≈-mode h (≈-trans c c′) = ≈-trans (≈-mode h c) (≈-mode h c′)

≈-pi : ∀ {σ m n q} {A A′ : Tm n} {B B′}
  → σ ⊢[ m ] A ≈ A′ → σ ⊢[ m ] B ≈ B′ → σ ⊢[ m ] pi q A B ≈ pi q A′ B′
≈-pi {B = B} cA cB = ≈-trans (go-A cA) (go-B cB)
  where
    go-A : ∀ {A A′ : Tm _} → _ ⊢[ _ ] A ≈ A′ → _ ⊢[ _ ] pi _ A B ≈ pi _ A′ B
    go-A (≈-step s) = ≈-step (⇛-pi s (⇛-refl _))
    go-A ≈-refl = ≈-refl
    go-A (≈-sym c) = ≈-sym (go-A c)
    go-A (≈-trans c c′) = ≈-trans (go-A c) (go-A c′)
    go-B : ∀ {A : Tm _} {B B′} → _ ⊢[ _ ] B ≈ B′ → _ ⊢[ _ ] pi _ A B ≈ pi _ A B′
    go-B (≈-step s) = ≈-step (⇛-pi (⇛-refl _) s)
    go-B ≈-refl = ≈-refl
    go-B (≈-sym c) = ≈-sym (go-B c)
    go-B (≈-trans c c′) = ≈-trans (go-B c) (go-B c′)

------------------------------------------------------------------------
-- Inversion. Rigid forms with different heads are not convertible, and
-- Π / ≡ are injective up to ≈.
------------------------------------------------------------------------

data Shape : Set where
  s-typ s-pi s-nat s-unit s-empty s-idt s-lam s-ze s-su s-one s-rfl : Shape
  s-prod s-pair : Shape

data HasShape {n} : Tm n → Shape → Set where
  h-typ   : HasShape typ s-typ
  h-pi    : ∀ {q A B} → HasShape (pi q A B) s-pi
  h-nat   : HasShape nat s-nat
  h-unit  : HasShape unit s-unit
  h-empty : HasShape empty s-empty
  h-idt   : ∀ {A a b} → HasShape (idt A a b) s-idt
  h-lam   : ∀ {q A t} → HasShape (lam q A t) s-lam
  h-ze    : HasShape ze s-ze
  h-su    : ∀ {t} → HasShape (su t) s-su
  h-one   : HasShape one s-one
  h-rfl   : HasShape rfl s-rfl
  h-prod  : ∀ {A B} → HasShape (prod A B) s-prod
  h-pair  : ∀ {a b} → HasShape (pair a b) s-pair

shape-⇛* : ∀ {σ m n} {t u : Tm n} {s}
  → HasShape t s → σ ⊢[ m ] t ⇛* u → HasShape u s
shape-⇛* h-typ r rewrite typ-⇛* r = h-typ
shape-⇛* h-pi r with pi-⇛* r
... | _ , _ , refl , _ , _ = h-pi
shape-⇛* h-nat r rewrite nat-⇛* r = h-nat
shape-⇛* h-unit r rewrite unit-⇛* r = h-unit
shape-⇛* h-empty r rewrite empty-⇛* r = h-empty
shape-⇛* h-idt r with idt-⇛* r
... | _ , _ , _ , refl , _ , _ , _ = h-idt
shape-⇛* h-lam r with lam-⇛* r
... | _ , _ , refl , _ , _ = h-lam
shape-⇛* h-ze r rewrite ze-⇛* r = h-ze
shape-⇛* h-su r with su-⇛* r
... | _ , refl , _ = h-su
shape-⇛* h-one r rewrite one-⇛* r = h-one
shape-⇛* h-rfl r rewrite rfl-⇛* r = h-rfl
shape-⇛* h-prod r with prod-⇛* r
... | _ , _ , refl , _ , _ = h-prod
shape-⇛* h-pair r with pair-⇛* r
... | _ , _ , refl , _ , _ = h-pair

shape-unique : ∀ {n} {t : Tm n} {s s′} → HasShape t s → HasShape t s′ → s ≡ s′
shape-unique h-typ h-typ = refl
shape-unique h-pi h-pi = refl
shape-unique h-nat h-nat = refl
shape-unique h-unit h-unit = refl
shape-unique h-empty h-empty = refl
shape-unique h-idt h-idt = refl
shape-unique h-lam h-lam = refl
shape-unique h-ze h-ze = refl
shape-unique h-su h-su = refl
shape-unique h-one h-one = refl
shape-unique h-rfl h-rfl = refl
shape-unique h-prod h-prod = refl
shape-unique h-pair h-pair = refl

≈-shape : ∀ {σ m n} {t u : Tm n} {s s′}
  → HasShape t s → HasShape u s′ → σ ⊢[ m ] t ≈ u → s ≡ s′
≈-shape ht hu c with ≈→join c
... | v , tv , uv = shape-unique (shape-⇛* ht tv) (shape-⇛* hu uv)

≈-pi-inj : ∀ {σ m n q q′} {A A′ : Tm n} {B B′}
  → σ ⊢[ m ] pi q A B ≈ pi q′ A′ B′
  → (q ≡ q′) × (σ ⊢[ m ] A ≈ A′) × (σ ⊢[ m ] B ≈ B′)
≈-pi-inj c with ≈→join c
... | v , tv , uv with pi-⇛* tv
...   | A″ , B″ , refl , rA , rB with pi-⇛* uv
...     | _ , _ , refl , rA′ , rB′ = refl , join→≈ rA rA′ , join→≈ rB rB′

≈-su-inj : ∀ {σ m n} {a b : Tm n}
  → σ ⊢[ m ] su a ≈ su b → σ ⊢[ m ] a ≈ b
≈-su-inj c with ≈→join c
... | v , tv , uv with su-⇛* tv
...   | _ , refl , ra with su-⇛* uv
...     | _ , refl , rb = join→≈ ra rb

-- su and ze are not convertible.
≈-su-ze : ∀ {σ m n} {a : Tm n} → σ ⊢[ m ] su a ≈ ze → ⊥
≈-su-ze c with ≈-shape h-su h-ze c
... | ()

≈-prod-inj : ∀ {σ m n} {A A′ B B′ : Tm n}
  → σ ⊢[ m ] prod A B ≈ prod A′ B′
  → (σ ⊢[ m ] A ≈ A′) × (σ ⊢[ m ] B ≈ B′)
≈-prod-inj c with ≈→join c
... | v , tv , uv with prod-⇛* tv
...   | _ , _ , refl , rA , rB with prod-⇛* uv
...     | _ , _ , refl , rA′ , rB′ = join→≈ rA rA′ , join→≈ rB rB′

≈-idt-inj : ∀ {σ m n} {A A′ a a′ b b′ : Tm n}
  → σ ⊢[ m ] idt A a b ≈ idt A′ a′ b′
  → (σ ⊢[ m ] A ≈ A′) × (σ ⊢[ m ] a ≈ a′) × (σ ⊢[ m ] b ≈ b′)
≈-idt-inj c with ≈→join c
... | v , tv , uv with idt-⇛* tv
...   | _ , _ , _ , refl , rA , ra , rb with idt-⇛* uv
...     | _ , _ , _ , refl , rA′ , ra′ , rb′ =
  join→≈ rA rA′ , join→≈ ra ra′ , join→≈ rb rb′

------------------------------------------------------------------------
-- Data types are rigid: a dty spine is not convertible to a form with
-- another head, and two convertible dty spines have the same head and
-- pointwise convertible arguments.
------------------------------------------------------------------------

infix 3 _⊢[_]_≈L_

data _⊢[_]_≈L_ (σ : Sig) (m : Mode) {n} : List (Tm n) → List (Tm n) → Set where
  ≈L-[] : σ ⊢[ m ] [] ≈L []
  ≈L-∷  : ∀ {a b as bs} → σ ⊢[ m ] a ≈ b → σ ⊢[ m ] as ≈L bs
    → σ ⊢[ m ] (a ∷ as) ≈L (b ∷ bs)

≈L-refl : ∀ {σ m n} (as : List (Tm n)) → σ ⊢[ m ] as ≈L as
≈L-refl [] = ≈L-[]
≈L-refl (a ∷ as) = ≈L-∷ ≈-refl (≈L-refl as)

≈L-sym : ∀ {σ m n} {as bs : List (Tm n)} → σ ⊢[ m ] as ≈L bs → σ ⊢[ m ] bs ≈L as
≈L-sym ≈L-[] = ≈L-[]
≈L-sym (≈L-∷ a as) = ≈L-∷ (≈-sym a) (≈L-sym as)

≈L-trans : ∀ {σ m n} {as bs cs : List (Tm n)}
  → σ ⊢[ m ] as ≈L bs → σ ⊢[ m ] bs ≈L cs → σ ⊢[ m ] as ≈L cs
≈L-trans ≈L-[] ≈L-[] = ≈L-[]
≈L-trans (≈L-∷ a as) (≈L-∷ b bs) = ≈L-∷ (≈-trans a b) (≈L-trans as bs)

join→≈L : ∀ {σ m n} {as bs vs : List (Tm n)}
  → σ ⊢[ m ] as ⇛L* vs → σ ⊢[ m ] bs ⇛L* vs → σ ⊢[ m ] as ≈L bs
join→≈L ⇛L*-[] ⇛L*-[] = ≈L-[]
join→≈L (⇛L*-∷ a as) (⇛L*-∷ b bs) = ≈L-∷ (join→≈ a b) (join→≈L as bs)

-- Spines with a data head have no rigid Shape (their head is app or dty
-- or ctor), so they are not convertible to a shaped term.
Spine-shape : ∀ {n} {h : Tm n} {as e s} → DHead h → Spine h as e → HasShape e s → ⊥
Spine-shape dh-ctor sp-[] ()
Spine-shape dh-dty sp-[] ()
Spine-shape _ (sp-snoc _) ()

≈-Spine-shape : ∀ {σ m n} {h : Tm n} {as t u s}
  → DHead h → Spine h as t → HasShape u s → σ ⊢[ m ] t ≈ u → ⊥
≈-Spine-shape hd sp hu c with ≈→join c
... | v , tv , uv with Spine-⇛* hd sp tv
...   | _ , sp′ , _ = Spine-shape hd sp′ (shape-⇛* hu uv)

-- A ctor spine and a dty spine are not convertible.
≈-ctor-dty : ∀ {σ m n} {i j k} {as bs : List (Tm n)} {t u}
  → Spine (ctor i j) as t → Spine (dty k) bs u → σ ⊢[ m ] t ≈ u → ⊥
≈-ctor-dty sp sp′ c with ≈→join c
... | v , tv , uv with Spine-⇛* dh-ctor sp tv | Spine-⇛* dh-dty sp′ uv
...   | _ , sp₁ , _ | _ , sp₂ , _ with Spine-unique head-ctor head-dty sp₁ sp₂
...     | () , _

≈-dty-inj : ∀ {σ m n} {i j} {as bs : List (Tm n)} {t u}
  → Spine (dty i) as t → Spine (dty j) bs u → σ ⊢[ m ] t ≈ u
  → (i ≡ j) × (σ ⊢[ m ] as ≈L bs)
≈-dty-inj sp sp′ c with ≈→join c
... | v , tv , uv with Spine-⇛* dh-dty sp tv | Spine-⇛* dh-dty sp′ uv
...   | _ , sp₁ , r₁ | _ , sp₂ , r₂ with Spine-unique head-dty head-dty sp₁ sp₂
...     | refl , refl = refl , join→≈L r₁ r₂

-- Convertible dty spines applied to convertible arguments.
≈-appsFrom : ∀ {σ m n} {f g : Tm n} {as bs}
  → σ ⊢[ m ] f ≈ g → σ ⊢[ m ] as ≈L bs → σ ⊢[ m ] appsFrom f as ≈ appsFrom g bs
≈-appsFrom c ≈L-[] = c
≈-appsFrom c (≈L-∷ a as) = ≈-appsFrom (≈-app c a) as
  where
    ≈-app : ∀ {σ m n} {f g a b : Tm n}
      → σ ⊢[ m ] f ≈ g → σ ⊢[ m ] a ≈ b → σ ⊢[ m ] app f a ≈ app g b
    ≈-app {g = g} {a = a} cf ca = ≈-trans (go-f cf) (go-a ca)
      where
        go-f : ∀ {f g : Tm _} → _ ⊢[ _ ] f ≈ g → _ ⊢[ _ ] app f a ≈ app g a
        go-f (≈-step s) = ≈-step (⇛-app s (⇛-refl _))
        go-f ≈-refl = ≈-refl
        go-f (≈-sym c) = ≈-sym (go-f c)
        go-f (≈-trans c c′) = ≈-trans (go-f c) (go-f c′)
        go-a : ∀ {a b : Tm _} → _ ⊢[ _ ] a ≈ b → _ ⊢[ _ ] app g a ≈ app g b
        go-a (≈-step s) = ≈-step (⇛-app (⇛-refl _) s)
        go-a ≈-refl = ≈-refl
        go-a (≈-sym c) = ≈-sym (go-a c)
        go-a (≈-trans c c′) = ≈-trans (go-a c) (go-a c′)
